### ISSUE TITLE
Cannot import 'FBSDKApplicationDelegate' after upgrade to v11

### ISSUE THREAD

**Issue by radko93** [thebergamo/react-native-fbsdk-next#317]
After updating to 11.0.0 I'm getting following error:
`Use of undeclared identifier 'FBSDKApplicationDelegate'`

React Native 0.69, with `use_frameworks` with everything working previously.

The example does not seem to import anything in the AppDelegate?

**Comment by mikehardy** [comment]
Huh - sorry to hear this, I'm obviously interested in use_frameworks compatibility as maintainer on react-native-firebase but I haven't integrated the new version here in my app yet to see how it goes. I have higher priority items to work on in the next few days, so hopefully someone else can investigate and find the root cause on it but in the absence of that I'll probably have a look in a week or so.

I'm not sure there's really an advantage to the new SDKs at the moment, so fine to stay on v10 of this module for now

**Comment by mikehardy** [comment]
So, they are converting to Swift, and my project at least is still in Objective-C which causes some funky things to happen. And header strangeness is exactly the sort of thing that happens when you use `use_frameworks!` as well.

I was able to fix this locally by changing:

```objective-c
#import <FBSDKCoreKit/FBSDKCoreKit.h>
```

to

```objective-c
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
```

Going to see if this will work for the non-`use_frameworks!` case as well. It only seems to be *necessary* for `use_frameworks!` but if it works for both then I can update the docs to just say "always do that" otherwise the docs get more complicated.

**Comment by mikehardy** [comment]
It appears to be strictly required for both cases, and the reason it was not detected is because the example app (which I use to qualify new releases) does not have any linking included in it, so it was a false-positive. I'll add that to the example and update the docs.

**Comment by mikehardy** [comment]
Release notes for v11 updated, example update and docs update pending CI
https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v11.0.0

**Comment by radko93** [comment]
Fantastic, thank you @mikehardy!

**Comment by HorbachAndrii** [comment]
@mikehardy I think we need to update the info in another place also.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/36758882/193575782-df93944d-d3e0-4382-8125-10d3b6c11624.png">

**Comment by HorbachAndrii** [comment]
I wasn't sure if I was right)))

**Comment by yanush** [comment]
Sorry to comment on a closed issue, but I also have a similar problem with ios build after upgrading from 10.1.0 to 11.0.1:
'FBSDKCoreKit/FBSDKApplicationDelegate.h' file not found
I have changed the import from `#import <FBSDKCoreKit/FBSDKCoreKit.h>` to `#import <FBSDKCoreKit/FBSDKCoreKit-swift.h>`, cleaned project, de-integrated pods, but it still fails. Any suggestions?
(Downgrading back to 10.1.0 fixes the build issue)

**Comment by HorbachAndrii** [comment]
> Sorry to comment on a closed issue, but I also have a similar problem with ios build after upgrading from 10.1.0 to 11.0.1: 'FBSDKCoreKit/FBSDKApplicationDelegate.h' file not found I have changed the import from `#import <FBSDKCoreKit/FBSDKCoreKit.h>` to `#import <FBSDKCoreKit/FBSDKCoreKit-swift.h>`, cleaned the project, de-integrated pods, but building still fails. Any suggestions? Downgrading back to 10.1.0 fixes the build issue, but I really want to update to the new facebook sdk

Do you have `#import <FBSDKCoreKit/FBSDKCoreKit.h>` in other places? 
Because if you have, you need replace in all places from `#import <FBSDKCoreKit/FBSDKCoreKit.h>` to `#import <FBSDKCoreKit/FBSDKCoreKit-swift.h>`

**Comment by yanush** [comment]
That's the only place I have it, and my platform ios is set to 12.4
Any other suggestions?

**Comment by minhajul-islam** [comment]
> That's the only place I have it, and my platform ios is set to 12.4 Any other suggestions?

Have you solved the issue

**Comment by yanush** [comment]
@minhajul-islam nope, still using 10.1.0 unfirtunately

**Comment by usmanrafique779** [comment]
I am facing this issue even after appliying the solution anhy help?

**Comment by ngioldasis** [comment]
> I am facing this issue even after appliying the solution anhy help?

Did you find any solution? I'm having the same issue (applied the solution, getting the same error)

**Comment by devartwa** [comment]
any solution?

**Comment by erickarn** [comment]
i'm having the same error, any solution yet? I tried everything

**Comment by damdafayton** [comment]
same error

**Comment by yaminichhabra** [comment]
any solution to this ? I am still facing this issue after applying all fixes mentioned above

**Comment by mouhsnimohamed** [comment]
Hi everyone,

I was struggling with this error for 3 days and tried everything I could find online. I finally managed to fix it by moving the SDK import, which was originally inside an Objective-C condition, to a different location.  **Before**
`
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

// Meta SDK
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
#import <AuthenticationServices/AuthenticationServices.h>
#import <SafariServices/SafariServices.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif
`
**After**
`
// Meta SDK
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
#import <AuthenticationServices/AuthenticationServices.h>
#import <SafariServices/SafariServices.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif
`

**Comment by mouhsnimohamed** [comment]
Hi everyone,

I was struggling with this error for 3 days and tried everything I could find online. I finally managed to fix it by moving the SDK import, which was originally inside an Objective-C condition, to a different location.  **Before**

> `
> **#ifdef FB_SONARKIT_ENABLED**
> #import <FlipperKit/FlipperClient.h>
> #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
> #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
> #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
> #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
> #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
> 
> // Meta SDK
> #import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
> #import <AuthenticationServices/AuthenticationServices.h>
> #import <SafariServices/SafariServices.h>
> 
> static void InitializeFlipper(UIApplication *application) {
>   FlipperClient *client = [FlipperClient sharedClient];
>   SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
>   [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
>   [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
>   [client addPlugin:[FlipperKitReactPlugin new]];
>   [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
>   [client start];
> }
> **#endif**
> `
> 

**After**

> 

> `
> // Meta SDK
> #import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
> #import <AuthenticationServices/AuthenticationServices.h>
> #import <SafariServices/SafariServices.h>
> 
> **#ifdef FB_SONARKIT_ENABLED**
> #import <FlipperKit/FlipperClient.h>
> #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
> #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
> #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
> #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
> #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
> 
> static void InitializeFlipper(UIApplication *application) {
>   FlipperClient *client = [FlipperClient sharedClient];
>   SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
>   [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
>   [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
>   [client addPlugin:[FlipperKitReactPlugin new]];
>   [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
>   [client start];
> }
> **#endif**
> `

**Comment by Kata-C** [comment]
> [@mikehardy](https://github.com/mikehardy) I think we need to update the info in another place also. <img alt="image" width="973" src="https://user-images.githubusercontent.com/36758882/193575782-df93944d-d3e0-4382-8125-10d3b6c11624.png">

It worked for me! I am using version 13.1.4 and it worked

**Comment by JRBARROZ** [comment]
Guys, if you still on this issue, take a look on first step of ios guide from facebook. You need to add a package attached to your project facebook-sdk-ios. If this error keeping and you already did everything, open xcode and see the package session, saw if the package faceboo-sdk-ios is **RED**, if is red color right click button and 'reset cache'.

**Comment by redionSpace** [comment]
https://github.com/thebergamo/react-native-fbsdk-next?tab=readme-ov-file#32-ios
this helped me
some things changed after v15.0.0 i guess but the official documentation kinda sucks
