### ISSUE TITLE
Upgrading to v13.0.0 , build failed for android

### ISSUE THREAD

**Issue by nemapranay** [thebergamo/react-native-fbsdk-next#524]
Android build is failing here

we are on

react-native:0.64.2
react-native-fbsdk-next: 13.0.0

After upgrading this repo from 6.2.0 to 13.0.0 its having issue with android

it worked fine in iOS but having issues with android.

as i am trying to run android build

react-native run-android

then build failed with :
issue:

app/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButton.java:66: error: cannot find symbol
mEventDispatcher.dispatchEvent(new RCTLoginButtonEvent(UIManagerHelper.getSurfaceId(context), getId(), event));
^
symbol: method getSurfaceId(ReactContext)
location: class UIManagerHelper

/RCTLoginButton.java:89: error: cannot find symbol
mEventDispatcher.dispatchEvent(new RCTLoginButtonEvent(UIManagerHelper.getSurfaceId(context), getId(), event));
^
symbol: method getSurfaceId(ReactContext)
location: class UIManagerHelper

app/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButton.java:101: error: cannot find symbol
mEventDispatcher.dispatchEvent(new RCTLoginButtonEvent(UIManagerHelper.getSurfaceId(context), getId(), event));
^
symbol: method getSurfaceId(ReactContext)

app/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButtonEvent.java:13: error: no suitable constructor found for Event(int,int)
super(surfaceId,viewTag);
^
constructor Event.Event() is not applicable
(actual and formal argument lists differ in length)
constructor Event.Event(int) is not applicable
(actual and formal argument lists differ in length)

app/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java:50: warning: non-varargs call of varargs method with inexact argument type for last parameter;
callback.invoke(null);

Like this 7 errors i got

Can some one please help here with solution ?

**Comment by NahuelRobles** [comment]
I have the same error!

**Comment by nemapranay** [comment]
@NahuelRobles  but for apple compliance we need signed SDK for which will have privacy manifest, as iOS and android version we need to keep same that is 13.0.0.

can u suggest here ?

**Comment by maxwellwachira** [comment]
Having the same issue. I have successfully built for iOS but the build fails for android with the following error message:
Failed to apply plugin 'com.facebook.react.rootproject'.
   > A problem occurred configuring project ':app'.
      > Failed to notify project evaluation listener.
         > org/jetbrains/kotlin/gradle/plugin/mpp/pm20/KotlinCompilationData

**Comment by nemapranay** [comment]
after upgrading react native to 0.71.19 it worked , Thanks

**Comment by dinhduongson** [comment]
I'm using react-native 0.63.3. How to fix this issue? 😭

**Comment by Anzormumladze** [comment]
> I'm using react-native 0.63.3. How to fix this issue? 😭

any solutions , i have same issue with same version
